server:
  port: 8080
  servlet:
    context-path: /api/v1/alojamiento

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ViviEstudb
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
